### ISSUE TITLE
user profile system for admin website for editing

### ISSUE THREAD

**Issue by sylvercodez** [hngi/expenseng#243]
![Screenshot (242)](https://user-images.githubusercontent.com/64742528/87952591-e6444280-caa1-11ea-9d9f-74773b1247e6.png)
the admin should be able to upload a profile picture and also add a biography using the profile section @EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by sylvercodez** [comment]
#287 if approved to continue i am going to to the backend to connect it all but i would need user to also have a fields for image in the database so images  can be changed and a default can also be used

**Comment by EphraimDev** [comment]
You're free

**Comment by AironDev** [comment]
Don't alter users table, but rather create a profiles table with user_id foreign key
create the relationship and cascade on delete

**Comment by sylvercodez** [comment]
no i didnt i only added fields cos profile is for users

**Comment by sylvercodez** [comment]
this also can be tested sir

**Comment by EphraimDev** [comment]
How do I add a pic?

**Comment by sylvercodez** [comment]
the user field for image is not accepting file same issue was in cabinet when you want to create a user .....you wont see file signal the form is not accepting file dont know why


so i removed mine instead of making it kinda confusing 
![Screenshot (293)](https://user-images.githubusercontent.com/64742528/88489635-aa274b00-cf95-11ea-8170-7789956095be.png)

**Comment by EphraimDev** [comment]
Most likely because you are not doing it the right way. Ask for help on the channel if you need help

**Comment by sylvercodez** [comment]
i have solved my issue..tension is a teacher
