### ISSUE TITLE
Cabinet CRUD

### ISSUE THREAD

**Issue by Ezeko** [hngi/expenseng#244]
As an admin I should be able to create cabinet, view cabinets created , edit and also delete cabinet members.

@EphraimDev

**Comment by EphraimDev** [comment]
Go ahead

**Comment by Ezeko** [comment]
#273

**Comment by EphraimDev** [comment]
I'll test and if satisfied, close it myself

**Comment by EphraimDev** [comment]
Is your changes on the live server? If it's not ask the devops to push it

**Comment by EphraimDev** [comment]
After pushing, inform me so I can test

**Comment by Ezeko** [comment]
okay

**Comment by Ezeko** [comment]
This can be tested on live server now @EphraimDev

**Comment by EphraimDev** [comment]
@Ezeko no pagination for this page
![Screenshot (52)](https://user-images.githubusercontent.com/30093122/88154848-3e448b80-cbff-11ea-862c-e0f1405fb50f.png)

**Comment by Ezeko** [comment]
There is pagination. Maybe it didn't load fully @EphraimDev

**Comment by Ezeko** [comment]
![Screenshot_2020-07-22-16-01-14-335_com android chrome](https://user-images.githubusercontent.com/31517324/88193452-98f8da00-cc35-11ea-9c8c-d0252417bf76.jpg)
Here's a live screenshot @EphraimDev

**Comment by EphraimDev** [comment]
I made a comment about this sometime ago. It shouldn't display the code but the ministry itself while the option tags can have the code as value
![Screenshot_2020-07-27 ExpenseNg admin dashboard(1)](https://user-images.githubusercontent.com/30093122/88499145-ef12a800-cfbc-11ea-93e6-ea1289c7ba95.png)

**Comment by Ezeko** [comment]
Noted
