### ISSUE TITLE
super admin dashboard functionality crud

### ISSUE THREAD

**Issue by ajibadeabd** [hngi/expenseng#245]
A Registration of a company,. admin/super admin should be able to delete edit and update the registered company.
@EphraimDev
![Screenshot_20200720-154103](https://user-images.githubusercontent.com/43596899/87954456-4dfb8d00-caa4-11ea-911d-2dacd3946388.png)

**Comment by ajibadeabd** [comment]
> A Registration of a company,. admin/super admin should be able to delete edit and update the registered company.
> 
> ![Screenshot_20200720-154103](https://user-images.githubusercontent.com/43596899/87954456-4dfb8d00-caa4-11ea-911d-2dacd3946388.png)

**Comment by Ezeko** [comment]
This already exist

**Comment by Ezeko** [comment]
![Screenshot_2020-07-20-15-47-08-728_com android chrome](https://user-images.githubusercontent.com/31517324/87955534-cc0c6380-caa5-11ea-9008-de53c4f2dd33.jpg)

**Comment by EphraimDev** [comment]
Are you sure this feature is not available yet?

**Comment by ajibadeabd** [comment]
I can't find it, it can only create, no update and delete
