### ISSUE TITLE
> A Registration of a company,. admin/super admin should be able to delete edit and update the registered company.   @EphraimDev

### ISSUE THREAD

**Issue by ajibadeabd** [hngi/expenseng#246]
> A Registration of a company,. admin/super admin should be able to delete edit and update the registered company.
> 
> ![Screenshot_20200720-154103](https://user-images.githubusercontent.com/43596899/87954456-4dfb8d00-caa4-11ea-911d-2dacd3946388.png)

_Originally posted by @ajibadeabd in https://github.com/hngi/expenseng/issues/245#issuecomment-661106269_

@EphraimDev

**Comment by EphraimDev** [comment]
Has this not been done already?
