### ISSUE TITLE
crud for people, making the list for people to have all cridentials

### ISSUE THREAD

**Issue by ajibadeabd** [hngi/expenseng#248]
![Screenshot_20200720-164259](https://user-images.githubusercontent.com/43596899/87957430-29a1af80-caa8-11ea-92f0-3a87a93f4f24.png)

displaying details of people creating updating deleting and editing

@EphraimDev

**Comment by EphraimDev** [comment]
What do you mean by all credentials?

**Comment by sylvercodez** [comment]
company_id | name | position | twitter | facebook | linkedin | avatar | email


what he means sir @EphraimDev 

when you click people in the website it is not navigating to any place just static

**Comment by ajibadeabd** [comment]
> What do you mean by all credentials?

when you click on people on the dashboard it should show people credentials like  name avatar|twitter and all

**Comment by EphraimDev** [comment]
Who are the people and why are they relevant to the app? Are they ministers, cabinet members, company ceos etc?

**Comment by ajibadeabd** [comment]
> Who are the people and why are they relevant to the app? Are they ministers, cabinet members, company ceos etc?

it is relevant to this app because it give detailed info of the person, it show your position you are, and all your social media accounts. 

@EphraimDev

**Comment by EphraimDev** [comment]
You didn't answer the first part of the question

**Comment by ajibadeabd** [comment]
> You didn't answer the first part of the question

the people connect all staff together, basically I can say people consist of staff ministry CEO too

@EphraimDev

**Comment by ajibadeabd** [comment]
> You didn't answer the first part of the question

the people connect all staff together, basically I can say people consist of staff ministry CEO too

@EphraimDev

**Comment by EphraimDev** [comment]
Not relevant. Not approved
