### ISSUE TITLE
[FEATURE REQUEST] Comments/Replies [view, edit, delete, flag] for Admin (Backend)

### ISSUE THREAD

**Issue by AironDev** [hngi/expenseng#249]
### Describe the solution you'd like
I'm already working on this, My first implementation (blade templates) had a significant effect on the loading time of the dashboard, to solve this problem, I will rather use VUE components to communicate with the API

@EphraimDev

**Comment by EphraimDev** [comment]
What are the operations for comments and replies please?

**Comment by AironDev** [comment]
View, Edit, Flag, Delete, Create

**Comment by EphraimDev** [comment]
Alright go ahead
