### ISSUE TITLE
[FEATURE REQUEST] Ministry and company search page

### ISSUE THREAD

**Issue by AnitaMuna** [hngi/expenseng#258]
Re-design the footer of the fg expense website as the right footer was not implemented

**Comment by AnitaMuna** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
I need more explanation please

**Comment by AnitaMuna** [comment]
At the footer of the website, there's a place that says profile and under it there is company search and ministry search and when you click on it nothing pops up..so I was hoping there should be a page to search for different companies and ministry.

**Comment by EphraimDev** [comment]
approved

**Comment by AnitaMuna** [comment]
Thank you
