### ISSUE TITLE
improving upload spreed sheet  UI and displaying file format of file to upload 

### ISSUE THREAD

**Issue by ajibadeabd** [hngi/expenseng#260]
re designing the upload.blade.php page , a page to upload an Excel spreadsheet to data base, including format 
to check before selecting the excel file

@EphraimDev

**Comment by EphraimDev** [comment]
Include the screenshot of the present state of the page

**Comment by ajibadeabd** [comment]
![Screenshot_20200720-192643](https://user-images.githubusercontent.com/43596899/87974060-5f06c700-cac1-11ea-8fe1-da45802f59b7.png)

**Comment by ajibadeabd** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
approved
