### ISSUE TITLE
Approve and Ignore Visitor Suggestions 

### ISSUE THREAD

**Issue by pepps01** [hngi/expenseng#262]
This involves:
     1. On Approve
           The the suggested cabinet  member would be added to the Cabinet Database Automatically
     
     2. On Ignore 
        The selected member would be removed and added as soft deletes.

**Comment by pepps01** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
approved

**Comment by pepps01** [comment]
@EphraimDev  I have been ejected from Slack. Since I am still in stage 6 and have been yet to be promoted to stage 7. Kindly reinstate me as I am working on this stage 7 task. As presented to you.
