### ISSUE TITLE
Search Page Missing [BUG]

### ISSUE THREAD

**Issue by Acel-01** [hngi/expenseng#263]
### Describe the bug

There is no search page on the website 
### To Reproduce

1. Go to any FGexpense page
2. Click on the search icon
3. See error

### Expected behavior

on click, it should direct to a search page

### Desktop (please complete the following information):

-   OS: Windows
-   Browser Google Chrome, Samsung brower

### Smartphone (please complete the following information):

-   Device: 
-   OS: Android
-   Browser ...
-   Version ...

**Comment by EphraimDev** [comment]
Approved

**Comment by papa28x4** [comment]
@EphraimDev Please is this search page different from this
https://github.com/hngi/expenseng/issues/258

**Comment by EphraimDev** [comment]
Yes and she said she was choosing another task

**Comment by Acel-01** [comment]
Hello sir 
I think you can close this issue 
I've made PRs and they have been merged
