### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nwokochahannah** [hngi/expenseng#264]
### Describe the bug

Some changes were made to the navbar design and I will be implementing it

### Expected behavior

A responsive navbar 

### Additional context

I would like to make the make its responsive behaviour a side bar and also to add a back to top icon to the homepage

**Comment by Nwokochahannah** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by Nwokochahannah** [comment]
Fixed was not added to this issue is there any problem with it
