### ISSUE TITLE
Addition of super admin role to the existing roles

### ISSUE THREAD

**Issue by delight500** [hngi/expenseng#265]
**Description:**

Currently the roles available on the website includes

- Admin

- Manager

- Editor

- User

There is a flaw in this roles system, as admins can add other admins to the project and in turn get removed by the new admin that was added.

This is not right so there should be 1 super admin account that will solve this.
As only a super admin would be able to add an admin and also remove him

This would restrict the admin access when creating users and assigning roles to them, as they would no longer be able to create new admins or make any existing user an admin only the super admin would have this privilege.

**So the addition of a super admin account is necessary**

**Comment by EphraimDev** [comment]
The admin should be the super admin since we have other roles

**Comment by delight500** [comment]
Other roles only have edit access they don't have access to create things @EphraimDev

**Comment by EphraimDev** [comment]
Admin should have that access. Anybody with admin access has the highest access

**Comment by delight500** [comment]
So for other role users to have create access they have to be made an admin, meaning they can remove the admin that added them and this is not proper @EphraimDev

**Comment by delight500** [comment]
That's y I want to add the super admin role sir

**Comment by EphraimDev** [comment]
What `create access` are you referring to? To create new user?

**Comment by delight500** [comment]
Yes to add new users and to add companies, ministries etc
@EphraimDev

**Comment by EphraimDev** [comment]
Only admin should have access to add new users.

**Comment by delight500** [comment]
What am saying sir is that new admins created by an admin can remove the admin that created them from the website which is not proper

**Comment by EphraimDev** [comment]
Choose another task please
