### ISSUE TITLE
Promotions

### ISSUE THREAD

**Issue by pepps01** [hngi/expenseng#266]
I have not been promoted yet. @EphraimDev . I have been kicked out of the internship. Please reinstate me.

**Comment by EphraimDev** [comment]
This is beyond me please. Why are you not in stage 7?

**Comment by pepps01** [comment]
I awaited my changes to be merged. I called your attention but you may have missed it.

**Comment by pepps01** [comment]
I just continued with the current stage 7 tasks. Until you get the chance to promote me.

**Comment by pepps01** [comment]
@EphraimDev I m hopeful.
