### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SkyC0der** [hngi/expenseng#267]
### Describe the bug
The carousel doesn't work and it has a scroll overflow 

### Desktop (please complete the following information):

![Screenshot from 2020-07-20 21-33-09](https://user-images.githubusercontent.com/44367769/87983685-acd6fb80-cad0-11ea-9ec6-117cbd1d708d.png)

-   OS: Ubuntu
-   Browser : Firefox

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by EphraimDev** [comment]
approved

**Comment by EphraimDev** [comment]
Is this completed and visible on expenseng.com?

**Comment by SkyC0der** [comment]
It has been completed but not visible on expenseng.com
