### ISSUE TITLE
[FEATURE REQUEST] Link Expense/ministry Mini-table to the db

### ISSUE THREAD

**Issue by papa28x4** [hngi/expenseng#268]
### Is your feature request related to a problem? Please describe.

The data on the mini-table at base of the expense/ministry page is still hard-coded on the page.

### Describe the solution you'd like

I want to create a controller method to calculate and return the annual total expenses incurred by all ministries for each of last 5 years(which in this case is 2016 - 2020) and populate the above-mentioned table.

**Comment by papa28x4** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
Until this is live, you are not allowed to open another issue

**Comment by EphraimDev** [comment]
Done

**Comment by EphraimDev** [comment]
Is this the section you are referring to here? Why am I seeing 2027-2031?
![Screenshot_2020-07-25 Ministry Expenses](https://user-images.githubusercontent.com/30093122/88458883-f46ed600-ce88-11ea-8f09-b5c72d55ec5e.png)

**Comment by papa28x4** [comment]
@EphraimDev This live server has issues. 
If the time (year) of server is correctly set , this shouldn't happen. I don't have this behavior on the test http://testexpenses.herokuapp.com/expense/ministry nor on the local.

**Comment by papa28x4** [comment]
I have been thinking about this mind boggling issue and it finally clicked. The problem is the database seed. Someone created seeds with payment dates up to 2031 which is practically impossible. You can't have a payment date for 2031 when we are still in 2020. The daily payments carry today's date not some futuristic date.

That said, in this case 2031 is most recent year and my code is working as expected. GIGO

![Screenshot_20200725-165523](https://user-images.githubusercontent.com/45360667/88461055-98ac4900-ce98-11ea-8165-34dfebae1691.png)

**Comment by papa28x4** [comment]
@EphraimDev
