### ISSUE TITLE
Set up a settings page for the admin

### ISSUE THREAD

**Issue by davidalenoghena** [hngi/expenseng#270]
### Is your feature request related to a problem? Please describe.
There is currently no settings page in the admin section

### Describe the solution you'd like
**I won't be implementing the functionalities, only the front end**
I will set up the page with general, notification and security features. 
For the general, an admin should be able to change the appearance of the dashboard, set email address to be used in sending mails, set sender name.
For notification; enable or disable pop up, silent or enable sound
For security; block a particular IP address
**Features unable to be implemented upon completion of the site will be scraped out**
**Please more features should be adviced**

**Comment by davidalenoghena** [comment]
@EphraimDev I would like to work on this as soon as the design is ready

**Comment by EphraimDev** [comment]
I have approved this for someone else

**Comment by davidalenoghena** [comment]
user profile system for admin website for editing (https://github.com/hngi/expenseng/issues/243)
This is the closest to my task I could find and this is for the profile.
![image](https://user-images.githubusercontent.com/43188489/88032749-4f759580-cb36-11ea-8a59-2fad97b03659.png)
The settings page is currently not linked to anything.
Just trying to be sure this task has been taken before I close it

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
I will close it after I have tested it on the liver server in a few minutes

**Comment by EphraimDev** [comment]
You can open another issue now
