### ISSUE TITLE
Cabinet crud

### ISSUE THREAD

**Issue by delight500** [hngi/expenseng#271]
create a page on the the dashboard where users can perform cabinet crud (create, retrieve, update and delete) @EphraimDev

**Comment by Ezeko** [comment]
These have been worked on. @delight500

**Comment by delight500** [comment]
@Ezeko i cant see it in the application folder neither is showing on the live website
we dont have cabinet page on the dashboard where admins can perform crud

**Comment by Ezeko** [comment]
Check previous issues. The PR has been made.
