### ISSUE TITLE
Recent activities and notification

### ISSUE THREAD

**Issue by delight500** [hngi/expenseng#275]
There should be a page where an admin would get notified anytime an action is carried out on the application 
eg : add a new user, delete a company, or uploading a new excel file etc

@EphraimDev

**Comment by EphraimDev** [comment]
Approved
It shouldn't be a page on it's own. Let there be an activity section on the dashboard that shows latest activities. Also the notification icon on the top right header of the admin should be useful here

**Comment by delight500** [comment]
Okay so should i build an activites page instead and update the notification icon with respect to 
The new activites @EphraimDev

**Comment by EphraimDev** [comment]
No need for a new page. Add it to the dashboard

**Comment by delight500** [comment]
Okay
