### ISSUE TITLE
[FEATURE REQUEST] Comments Section Improvements

### ISSUE THREAD

**Issue by goodhands** [hngi/expenseng#276]
### Is your feature request related to a problem? Please describe.

Currently a visitor can only comment after giving their names and email which will be displayed on the website alongside their comments, and also a visitor can't edit or delete or flag other comments. This feature will enable all that.

### Describe the solution you'd like

- A visitor should be able to comment as an anonymous user
- A visitor should be able to edit their comment
- A visitor should be able to delete their comment
- A visitor should be able to flag other comments

**Comment by goodhands** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved
