### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by webdott** [hngi/expenseng#286]
### Describe the bug

Breadcrumbs have no margin to the left and on some pages, have different colors(On the about us page).

### To Reproduce

For margin issues:
1. Go to 'home'
2. Click on 'ministry drop-down'
3. Click on either 'expenditure reports' or 'ministry expense'
4. breadcrumb is just below header.
5. See error

For color issues:
1. Go to 'home'
2. Click on 'About Us'
3. breadcrumb is just below header.
### Expected behavior

The breadcrumb menu is expected to have a reasonable margin to the left for better UI and is also meant to maintain the same color.(On some pages, it is green. On others, blue)

### Screenshots
margins:
![bug1](https://user-images.githubusercontent.com/52088600/88049167-8fe00e00-cb4c-11ea-8bef-e9e248574e04.png)

![bug2](https://user-images.githubusercontent.com/52088600/88049169-92426800-cb4c-11ea-934f-00f8f37377c1.png)

Color issues:

![bug3](https://user-images.githubusercontent.com/52088600/88049170-92dafe80-cb4c-11ea-9a0f-23c9956864ee.png)

### Desktop (please complete the following information):

-   OS: Ubuntu
-   Browser: chrome
-   Version: 22

### Smartphone (please complete the following information):

-   Device: Xiaomi Redmi Note 8
-   OS: Andriod
-   Browser Chrome
-   Version: 22

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
Margins are needed here. Also We need a better tag without the underscore
![Screenshot (54)](https://user-images.githubusercontent.com/30093122/88158796-61be0500-cc04-11ea-92aa-58f67d08c108.png)

**Comment by webdott** [comment]
I have fixed those issues since
Changes haven't just been reflected on the server

And about the tags without underscore, I'll look into it now
