### ISSUE TITLE
[FEATURE REQUEST]- Accessibility  Page

### ISSUE THREAD

**Issue by SkyC0der** [hngi/expenseng#295]
### Is your feature request related to a problem? Please describe.

I would like to implement the new designs of the accessibility and its respective route.

**Comment by EphraimDev** [comment]
I don't understand this issue

**Comment by SkyC0der** [comment]
![Screenshot from 2020-07-21 21-19-57](https://user-images.githubusercontent.com/44367769/88102778-05250080-cb98-11ea-805a-5b790bf2d589.png)
I would like to implement the accessibility page design

**Comment by EphraimDev** [comment]
Approved
