### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by webdott** [hngi/expenseng#297]
### Is your feature request related to a problem? Please describe.

I want to implement the front-end  of the freedom of act page design.

### Describe the solution you'd like

Full implementation of the page

### Additional context

![FOIA](https://user-images.githubusercontent.com/52088600/88102049-d9554b00-cb96-11ea-9fb9-a24a97c865cd.png)

**Comment by EphraimDev** [comment]
Approved
