### ISSUE TITLE
[Filter Modal on Expense/Ministry Page doesn't work]

### ISSUE THREAD

**Issue by papa28x4** [hngi/expenseng#299]
### Describe the bug

The filter modal on this page does nothing when applied.

### Expected behavior

The data displayed by table should be modified each time a filter is applied. It should display content that matches the specified date, month or year. I intend implement this functionality.

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
Is the table containing dummy data or from the database?

**Comment by papa28x4** [comment]
@EphraimDev  It's from the database. You can check the file. There's no hardcoded data on the page.

**Comment by EphraimDev** [comment]
From what?

**Comment by EphraimDev** [comment]
The pagination is acting funny. I don't understand it

**Comment by papa28x4** [comment]
How is it behaving?

**Comment by EphraimDev** [comment]
No matter the number I click, it doesn't leave the page 1.
![Screenshot_2020-07-25 Ministry Expenses(1)](https://user-images.githubusercontent.com/30093122/88459243-c4750200-ce8b-11ea-8c85-528537fd1bf8.png)

**Comment by EphraimDev** [comment]
Filter works well. How do I clear the filter to return all the data back?

**Comment by papa28x4** [comment]
When you said funny I thought the pagination some how had started working but with some inconsistencies. Pagination doesn't work on the live, because pagination depends on query strings. That server doesn't support it

**Comment by papa28x4** [comment]
I didn't think of that maybe because the design didn't include it. I'll have to add a button to reset

**Comment by EphraimDev** [comment]
Yes do. 
Then Do I have to select a date if I just want to filter by amount only?

**Comment by papa28x4** [comment]
I will relax the control so a user can just sort by amount only
