### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by odizee** [hngi/expenseng#320]
### Describe the bug

Ministry Expense Table Pagination is not responsive on mobile. It overflows. 

### Expected behavior

The pagination should be implemented in a way that will not make the page overflow.

### Screenshots
![IMG_20200722_203446](https://user-images.githubusercontent.com/66241926/88221103-e25c2000-cc5b-11ea-8862-269ce7e9b379.jpg)

**Comment by odizee** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by odizee** [comment]
@EphraimDev someone else has fixed this issue.

**Comment by EphraimDev** [comment]
Oh ok. Look for another
