### ISSUE TITLE
Contact Us Feature

### ISSUE THREAD

**Issue by davidalenoghena** [hngi/expenseng#322]
### Is your feature request related to a problem? Please describe.
The contact us currently doesn't function

### Describe the solution you'd like
I would make it work and emails will be sent to my mail for now till we have set up an official mail for the site

### Additional context
![image](https://user-images.githubusercontent.com/43188489/88223149-ea698f00-cc5e-11ea-989a-dcc3cbe9e416.png)

**Comment by davidalenoghena** [comment]
I would like to work on this @EphraimDev
Is it okay to direct the mails to my gmail account for now?

**Comment by EphraimDev** [comment]
Use expenseng@gmail.com for the live server. Your local can use your email

**Comment by EphraimDev** [comment]
Approved
