### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by webdott** [hngi/expenseng#329]
### Is your feature request related to a problem? Please describe.

I would like to implement the privacy policy page

### Describe the solution you'd like

Full frontend implementation of the privacy policy design page

### Additional context

![Privacy Policy](https://user-images.githubusercontent.com/52088600/88242256-940f4700-cc84-11ea-8de3-3a9848c653db.png)

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
@leeCodes-bit

**Comment by webdott** [comment]
Is this person doing this page sir or I should go ahead?

**Comment by EphraimDev** [comment]
Go ahead
