### ISSUE TITLE
Bug in ministry profile page 

### ISSUE THREAD

**Issue by Nwokochahannah** [hngi/expenseng#330]
### Describe the bug

When a card in ministries is clicked (locally) the ministry profile page continues loading, when itis clicked on the live link the page does not open

### Expected behavior

For the ministry profile of any company to open without any hitches 

### Screenshots

![Screenshot_20200722-170150](https://user-images.githubusercontent.com/62136073/88246838-a47aee00-cc93-11ea-8043-713a2ac44b4c.png)

### Desktop (please complete the following information):

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by Nwokochahannah** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved
