### ISSUE TITLE
Admin settings page

### ISSUE THREAD

**Issue by leeCodes-bit** [hngi/expenseng#331]
### Describe the bug

the login and register page is not responsive and needs fixing.

### Screenshots

![WhatsApp Image 2020-07-23 at 3 10 47 AM](https://user-images.githubusercontent.com/51709108/88246936-fb80c300-cc93-11ea-82ca-0db5049a856e.jpeg)
![WhatsApp Image 2020-07-23 at 3 10 53 AM](https://user-images.githubusercontent.com/51709108/88246941-fd4a8680-cc93-11ea-9e52-68dfb170a5cf.jpeg)
.

### Desktop (please complete the following information):

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by EphraimDev** [comment]
Approved

**Comment by EphraimDev** [comment]
However I'm not sure the admin needs a register page. Can you also add a login link to the footer of the website because the user journey is somehow as there's no login link on the website

**Comment by leeCodes-bit** [comment]
Ok will do that sir

**Comment by leeCodes-bit** [comment]
i just made a pr sir
