### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by leeCodes-bit** [hngi/expenseng#336]
### Describe the bug

A wrong footer logo and faq not included.

### Screenshots

![2](https://user-images.githubusercontent.com/51709108/88253164-d185cb80-cca8-11ea-9d33-7a2b5f43df35.PNG)

### Desktop (please complete the following information):

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by EphraimDev** [comment]
Approved

**Comment by leeCodes-bit** [comment]
completed and already merged
