### ISSUE TITLE
Contact Us Page Icons. 

### ISSUE THREAD

**Issue by odizee** [hngi/expenseng#340]
### Describe the bug
The icons on the contact us page are overlapping with the details, on mobile screen. 

### Expected behavior

It needs to align left of their details or bottom. 

### Screenshots

![IMG_20200722_203416](https://user-images.githubusercontent.com/66241926/88258719-aefbae80-ccb8-11ea-84fb-c83f916a4a5a.jpg)

**Comment by EphraimDev** [comment]
Approved
