### ISSUE TITLE
Addition of notification preview modal to the recent activity table

### ISSUE THREAD

**Issue by delight500** [hngi/expenseng#341]
On the notification table when a view is clicked it should bring out a modal that shows the full details of that particular activity, details like

- The name of the person that carried out the activity with the privilege level of that particular user

- the date and time that activity was carried out

- full description of the activity carried out

![Screenshot_20200723-083025](https://user-images.githubusercontent.com/54745498/88262163-9347d680-ccbf-11ea-8f61-cc2bee412286.png)

**Comment by delight500** [comment]
When any of the tabs are clicked this modal should come up
Showing the details I listed above, as this would help to keep track of actions performed by users in the admin area
And who performed the action


@EphraimDev

**Comment by delight500** [comment]
@EphraimDev please approve this so i can start working

**Comment by EphraimDev** [comment]
Approved
