### ISSUE TITLE
Back-to-top Button

### ISSUE THREAD

**Issue by Acel-01** [hngi/expenseng#342]
### Describe the bug

On the about us page, the back to top button is positioned below the footer

### To Reproduce

1. Go to 'About Us' page
2. Scroll down to the end of the page
3. See error

### Expected behavior

It should be styled as the one on the home page is

### Screenshots

![FG Expense - Home (1)](https://user-images.githubusercontent.com/60946455/88268673-bd52c600-ccca-11ea-84e3-199cf520ba1d.png)
![FG Expense - Home](https://user-images.githubusercontent.com/60946455/88268696-c2b01080-ccca-11ea-9a0a-730ae9a0c1d1.png)

**Comment by EphraimDev** [comment]
Approved
