### ISSUE TITLE
Logo on header

### ISSUE THREAD

**Issue by Acel-01** [hngi/expenseng#343]
### Describe the bug

on click, it directs to a missing index.html page

### To Reproduce

1. Go to any page on expenseng.com
2. Click on the expenseng logo
3. See error

### Expected behavior

on click, the expenseng logo should direct to the homepage not index.html(that's apparently missing)

### Screenshots

![Not Found](https://user-images.githubusercontent.com/60946455/88269639-4b7b7c00-cccc-11ea-951a-f31f9a4eba60.png)

**Comment by EphraimDev** [comment]
Approved
