### ISSUE TITLE
[FEATURE REQUEST] PAYMENTS CRUD

### ISSUE THREAD

**Issue by AironDev** [hngi/expenseng#346]
### Is your feature request related to a problem? Please describe.
* What we currently  have as Expenses  rather  matches Payments Model and Database Design
* Payments are done by MDAs, so that should be considered as Expenses

---

### Describe the solution you'd like
1. I will create a Payments CRUD
2. Correct the Recent Expenses on dashboard to reflect data from payments table

---
### Additional context

Payments TableDesign
![image](https://user-images.githubusercontent.com/29748407/88271965-e7f34d80-cccf-11ea-8695-ae25f5592fbe.png)

Expense Table (data does not match)
![image](https://user-images.githubusercontent.com/29748407/88272400-8da6bc80-ccd0-11ea-96bf-a410b4da3fd3.png)

@EphraimDev

**Comment by EphraimDev** [comment]
Approved
