### ISSUE TITLE
PARSING AND PERSISTING EXCEL SHEETS

### ISSUE THREAD

**Issue by Ezeko** [hngi/expenseng#347]
The site should be able to parse and persist crawled sheets at specific intervals. @EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by Ezeko** [comment]
#385

**Comment by Ezeko** [comment]
#397

**Comment by Ezeko** [comment]
#422 
![Screenshot (124)](https://user-images.githubusercontent.com/31517324/88468641-6d4c4d00-cede-11ea-9f57-754ce97b7977.png)
