### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Ezeko** [hngi/expenseng#35]
Backend get Expenditure reports from database and display to frontend

### SOLUTION
create a controller to handle the DB read and return to view

### Describe alternatives you've considered
The method can also be applied on the pages controller

**Comment by sosualfred** [comment]
Can i work on it

**Comment by Ezeko** [comment]
It's been worked on already

**Comment by sosualfred** [comment]
Make sure you indicate the assignee next time. And close the issue.
