### ISSUE TITLE
Implementation of settings page

### ISSUE THREAD

**Issue by SkyC0der** [hngi/expenseng#352]
### Is your feature request related to a problem? Please describe.

I would like to implement the settings page
![Screenshot from 2020-07-23 13-38-25](https://user-images.githubusercontent.com/44367769/88287382-1ed65d00-ccea-11ea-8353-521e6243e9cd.png)

**Comment by EphraimDev** [comment]
Are you sure it hasn't been done?

**Comment by SkyC0der** [comment]
It was done before the design was released. So I would like to refactor the current page to match the design

**Comment by EphraimDev** [comment]
Ok
