### ISSUE TITLE
ministry and contractors page breadcrumbs

### ISSUE THREAD

**Issue by leeCodes-bit** [hngi/expenseng#356]
### Describe the bug

ministry and contractors page breadcrumbs.

### Screenshots

![5](https://user-images.githubusercontent.com/51709108/88297537-ee95bb00-ccf7-11ea-9d5b-559b40436f2e.PNG)
![6](https://user-images.githubusercontent.com/51709108/88297545-f05f7e80-ccf7-11ea-8261-b63c569dcd6f.PNG)
![7](https://user-images.githubusercontent.com/51709108/88297548-f0f81500-ccf7-11ea-9b20-2bcd4c1568ef.PNG)
![8](https://user-images.githubusercontent.com/51709108/88297553-f190ab80-ccf7-11ea-9bf4-6b16de9ffeaf.PNG)

### Desktop (please complete the following information):

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by EphraimDev** [comment]
Approved
