### ISSUE TITLE
 Fix tab and placeholder text on contractors page 

### ISSUE THREAD

**Issue by odizee** [hngi/expenseng#359]
### Describe the bug

The companies and total awards tab goes left and doesn't align well with the graphs. Also, the placeholder text in the search input form has a different font family.
@EphraimDev 

![Screenshot (45)](https://user-images.githubusercontent.com/66241926/88307834-4afed780-cd04-11ea-9cf5-4b02e4c8d775.png)

**Comment by EphraimDev** [comment]
Approved
