### ISSUE TITLE
[BUG] on ministry and {ministries}

### ISSUE THREAD

**Issue by davidalenoghena** [hngi/expenseng#376]
![image](https://user-images.githubusercontent.com/43188489/88374087-0a00d480-cd91-11ea-9837-82e063c47c83.png)
Title of the ministry card currently missing

![image](https://user-images.githubusercontent.com/43188489/88374148-27ce3980-cd91-11ea-9b77-5edfb6e98ce6.png)
Current breadcrumb is wrong. Should show the particular ministry being viewed

**Comment by EphraimDev** [comment]
Approved
