### ISSUE TITLE
[FEATURE REQUEST] Implement Charts for Ministry Expenditure section of the Home Page

### ISSUE THREAD

**Issue by papa28x4** [hngi/expenseng#384]
### Is your feature request related to a problem? Please describe.

Currently, Ministry Expenditures select drop-down on the home page still has dummy options. Also, the chart displayed is static. 

### Describe the solution you'd like

I intend to connect the drop-down to the backend so it shows the list of ministries. And when a user selects a ministry, the chart re-renders to show data that pertains to that ministry. 

![ministry_expenditure](https://user-images.githubusercontent.com/45360667/88390107-a6d26a80-cdaf-11ea-9205-57290e200eb1.PNG)

**Comment by EphraimDev** [comment]
Approved
