### ISSUE TITLE
adding a change password for user in profile page

### ISSUE THREAD

**Issue by sylvercodez** [hngi/expenseng#389]
admin have the ability to change password using the dashboard but users should be able to also change there password via profile

**Comment by sylvercodez** [comment]
![Screenshot (259)](https://user-images.githubusercontent.com/64742528/88402399-f8382500-cdc2-11ea-814f-ddca4f46055d.png)
how it will look like @EphraimDev

**Comment by sylvercodez** [comment]
and another undone works can be added for me to do i am adapting now

**Comment by EphraimDev** [comment]
Approved

**Comment by sylvercodez** [comment]
also done with the password change
