### ISSUE TITLE
Adding Pulse effects to scroll down button

### ISSUE THREAD

**Issue by odizee** [hngi/expenseng#393]
### Is your feature request related to a problem? Please describe.

I would like to add pulse effects to the big button at the home page to make users know that it is functional.
![IMG_20200724_184514](https://user-images.githubusercontent.com/66241926/88419917-e6b04680-cddd-11ea-86dc-1d01a64c8b49.jpg)

**Comment by EphraimDev** [comment]
Is the button actually functional?

**Comment by odizee** [comment]
Yes. I thought if it will be okay if it has an effect. Like a pulse so it gets user attention. 
And I noticed that when it's clicked it just vanishes down to the section referenced, unlike the scroll up where you see that it's actually scrolling up the page.
