### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sylvercodez** [hngi/expenseng#403]
when you click on the dashboard logo in the nav bar it is not working i can fix it pending the time i see another task can i runcheck all sections and list all the click-ables and functions that are not working??

**Comment by sylvercodez** [comment]
![Screenshot (272)](https://user-images.githubusercontent.com/64742528/88442092-11fd5a80-ce0b-11ea-8a8d-fd0112824693.png)

**Comment by sylvercodez** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Yes please but pull the latest and check on your local

**Comment by sylvercodez** [comment]
ok

**Comment by sylvercodez** [comment]
im done withe first check and also the dashboard logo

**Comment by EphraimDev** [comment]
Add a picture of what you mean by dashboard logo please

**Comment by sylvercodez** [comment]
![Screenshot (270)](https://user-images.githubusercontent.com/64742528/88489576-4735b400-cf95-11ea-8f1c-01c2d514fd79.png)

the small four boxes was not redirecting anywhere before i fixed it will add my pr now of it

**Comment by sylvercodez** [comment]
https://github.com/hngi/expenseng/pull/406 this is my merged pr
