### ISSUE TITLE
Admin sidebar sheet

### ISSUE THREAD

**Issue by Ezeko** [hngi/expenseng#426]
As an Admin, I should be able to see sheets scrapped from open treasury and download at will. #425 @EphraimDev 
![Screenshot (121)](https://user-images.githubusercontent.com/31517324/88468632-42fa8f80-cede-11ea-8088-94ac981ed407.png)

**Comment by EphraimDev** [comment]
1. Can we also have an icon that when clicked, parses the particular sheet and stores it content in the database? This should be beside the download icon
2. There's no pagination on the page. I want to be able to also filter or search for certain sheets (http://testexpenses.herokuapp.com/admin/sheets)
3. Status: New, what does this mean?

**Comment by EphraimDev** [comment]
How come pagination is available on your local but not on heroku? Same with the cabinet page

**Comment by EphraimDev** [comment]
I see why
```Uncaught TypeError: $(...).DataTable is not a function```
I guess you have to try another way to include the plugin

**Comment by Ezeko** [comment]
All is included. I'll check it here now

**Comment by Ezeko** [comment]
> How come pagination is available on your local but not on heroku? Same with the cabinet page

Maybe it doesn't load fully. Cos there is pagination on the cabinet page online

**Comment by Ezeko** [comment]
![Screenshot_2020-07-27-07-50-54-460_com android browser](https://user-images.githubusercontent.com/31517324/88512745-f054cc80-cfde-11ea-8251-9b50820dac5b.jpg)
This is what I have on my phone

**Comment by Ezeko** [comment]
> 1. Can we also have an icon that when clicked, parses the particular sheet and stores it content in the database? This should be beside the download icon
> 2. There's no pagination on the page. I want to be able to also filter or search for certain sheets (http://testexpenses.herokuapp.com/admin/sheets)
> 3. Status: New, what does this mean?

New means not parsed or fresh sheet

**Comment by Ezeko** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/31517324/88564644-58c99b00-d02b-11ea-8d2f-100588ed5b2c.png)
@EphraimDev
