### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Nwokochahannah** [hngi/expenseng#446]
### Screenshots

![Screenshot (73)](https://user-images.githubusercontent.com/62136073/88508269-4a04c900-cfd6-11ea-93ba-1885471446e2.png)
![Screenshot_2020-07-27 FG Expense - Home(3)](https://user-images.githubusercontent.com/62136073/88508277-4ec97d00-cfd6-11ea-97b3-5242154bf4df.png)

### Work to be done
 changing the tab settings of the expense report page, 
making the cards in ministry and contractors page clickable, 
making the graph in the latest government section four in a row and
fixing the join this conversation section

**Comment by Nwokochahannah** [comment]
Webdot has made changes to the issue I raised before so I will be working on this

**Comment by Nwokochahannah** [comment]
@EphraimDev

**Comment by webdott** [comment]
@Nwokochahannah Thanks.
 I have made the cards clickable already though
