### ISSUE TITLE
[BUG] Replace dummy data on Latest Government expense section

### ISSUE THREAD

**Issue by SkyC0der** [hngi/expenseng#471]
### Describe the bug
I would like to replace dummy data on the home section of the project with accurate data from the db

### Desktop (please complete the following information):

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Comment by davidalenoghena** [comment]
Edit this title to be more explanatory

**Comment by EphraimDev** [comment]
Which part of the home page? Some have been done already

**Comment by SkyC0der** [comment]
![j](https://user-images.githubusercontent.com/44367769/88726476-b3472200-d125-11ea-9ced-8d808b38e10e.png)
Latest Government expense section
