### ISSUE TITLE
Site usage statistics and site  traffic counter

### ISSUE THREAD

**Issue by delight500** [hngi/expenseng#493]
Good morning @EphraimDev  I want to add this feature to our dashboard, that tracks the amount visitors that visits our site and the amount of times our site is visited daily.
I will also display what browser is used to open our site the most so we can check for responsiveness across top browsers, and I will display all this info with charts so we would get our weekly traffic and yearly traffic data plotted out.

**Comment by EphraimDev** [comment]
Go ahead
