### ISSUE TITLE
[BUG] Documentation still speaks about Larave Framework

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#612]
### Describe the bug

If you visit here: https://github.com/expenseng/expenseng you will see that the repo README.txt still reads as if it's a laraavel application

**Comment by Ezeko** [comment]
<img width="1440" alt="Screenshot 2020-09-09 at 14 36 38" src="https://user-images.githubusercontent.com/31517324/92605807-1346f180-f2aa-11ea-86db-b88a80c5cdee.png">
This is expenseng specific readme
