### ISSUE TITLE
[BUG] The top menu jumps around when you hover

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#613]
### Describe the bug

IF you go here: https://expenseng.com/ and hover your mouse over the menu at the top you will notice that the menu jumps around

### To Reproduce

1. Go to https://expenseng.com/
2. Hover your mouse over the menu

### Expected behavior

IT should not jump around

### Screenshots

![image](https://user-images.githubusercontent.com/373021/91712103-61137980-eb87-11ea-81bb-cc53df42ff37.png)

### Desktop (please complete the following information):

-   OS: Windows 10
-   Browser Chrome
-   Version Latest

**Comment by papa28x4** [comment]
Please review @markessien

**Comment by markessien** [comment]
Fixed
