### ISSUE TITLE
[FEATURE REQUEST] Change the title on Ministry Page to Expenses of Government Ministries in Nigeria

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#620]
[FEATURE REQUEST] Change the title on this page: https://expenseng.com/ministries to Expenses of Government Ministries in Nigeria

**Comment by charleyvibez** [comment]
Fixed, please kindly close this issue @EphraimDev

**Comment by ihechiwilliams** [comment]
kindly review @markessien

**Comment by markessien** [comment]
Good
