### ISSUE TITLE
[FEATURE REQUEST] Add Basic Filtering to Ministry Page

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#621]
On the ministry page (here https://expenseng.com/ministries) the default view should show how much expenditure each ministry had in the last complete month, with the largest expense ministry being sorted to the top.

Design and add tabs (NOT a dropdown) that allows me to show amount spent in 2020 or all time.

**Comment by papa28x4** [comment]
@markessien please review

**Comment by markessien** [comment]
Excellent!
