### ISSUE TITLE
[FEATURE REQUEST] Change URL of all expenses to be /expenses

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#623]
On this page: https://expenseng.com/expense/report change the URL to https://expenseng.com/expenses/. This will always list all expenses, with the latest at the top.

**Comment by ihechiwilliams** [comment]
issues fixed, kindly review @markessien

**Comment by ihechiwilliams** [comment]
@EphraimDev kindly reopen this issue
@markessien please review and close

**Comment by markessien** [comment]
The /report is still existent. These two pages pretty much do exactly the same thing.
