### ISSUE TITLE
[BUG] The URLs to the ministries should not be capitalised

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#629]
On this page https://expenseng.com/ministries/ hovering over the ministry links shows that the urls being linked to are capitalised, e.g this: https://expenseng.com/ministries/Trade https://expenseng.com/ministries/Petroleum.

Only small letter urls should work, the others should 404.

**Comment by papa28x4** [comment]
@markessien please review

**Comment by markessien** [comment]
Great!
