### ISSUE TITLE
[BUG] Move the Government Twitter handle page to the footer

### ISSUE THREAD

**Issue by markessien** [hngi/expenseng#639]
It's not needed at the top

**Comment by ihechiwilliams** [comment]
fixed, kindly close it @EphraimDev

**Comment by EphraimDev** [comment]
@charleyvibez Mark will be doing the closing, that's why I reopened them back.

**Comment by ihechiwilliams** [comment]
okay sir,

**Comment by ihechiwilliams** [comment]
Kindly review @markessien

**Comment by markessien** [comment]
Good

**Comment by ihechiwilliams** [comment]
@EphraimDev i guess you can close this issue since mark has reviewed it
